definitions:
  handlers.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  handlers.Response:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /check-health:
    get:
      description: Its used to know if the server is working correctly
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Check Health
      tags:
      - Internal
swagger: "2.0"
